### ISSUE TITLE
大佬有没有遇到过/deep/、>>>等深度选择器无法使用的情况？

### ISSUE THREAD

**Issue by BBBBBenk** [CroMarmot/kylin-demo-bugs#1]
我使用 `npm run dev:preview` 在chrome的控制台看，这个/deep/不能被less-loader或者css-loader识别

> ### Code
```less
 .load-more {
    /deep/ .load-top {
        color: red;
    }
 }
```

> ### Compile
```less
 .load-more /deep/ .load-top[data-v-18dgh9a] {
        color: red;
 }
```

> ### 正常来说应该是这样
```less
.load-more[data-v-18dgh9a] .load-top {
        color: red;
 }
```

直接下载他的demo 就可以复现 在不进行任何配置的情况下，他的样式穿透是无法使用的，不知道为什么
